### ISSUE TITLE
Less strict commas

### ISSUE THREAD

**Issue by tomaskulich** [ooflorent/graphql-parser#8]
currently, the parser requires commas between different parameters. Absence of commas or tailing commas is considered bad, although GraphQL accepts it:

Good:

```
{
  post(
    aaa: "aaa",
    bbb: "bbb",
    ccc: "ccc"
){id}}
```

Bad for parser, good for GraphQL (trailing comma)

```
{
  post(
    aaa: "aaa",
    bbb: "bbb",
    ccc: "ccc",
){id}}
```

Bad for parser, good for GraphQL (no commas)

```
{
  post(
    aaa: "aaa"
    bbb: "bbb"
    ccc: "ccc"
){id}}
```

**Comment by joanrodriguez** [comment]
+1

**Comment by ooflorent** [comment]
What's the motivation here? Why not using Facebook's `graphql-js`?
This library is completely out-of-date and would need a major rewrite to be spec compliant.

**Comment by fbernhard** [comment]
@ooflorent: we like that your library can parse a graphql query into a JSON object. Unfortunately our queries can be of any of the above mentioned formats

**Comment by joanrodriguez** [comment]
Is there a function in Facebook's app that allows you to transform a GraphQL string into a Json object??

**Comment by ooflorent** [comment]
Yes!

``` js
import { parse } from 'graphql/language/parser';
```

**Comment by fbernhard** [comment]
May we should move it over there, but afaik this parses the query into an ast Document, not a JSON.

**Comment by ooflorent** [comment]
The `Document` AST is a plain object so it is a JSON.

**Comment by tomaskulich** [comment]
I didn't notice the parsing capabilities of the official library. Thank you for pointing this out.

**Comment by tomaskulich** [comment]
@ooflorent: maybe it'd be nice to state this explicitly in the readme? :)
